local ADDONNAME, ns = ...
if not ns then
    _G[ADDONNAME] = _G[ADDONNAME] or {}
    ns = _G[ADDONNAME]
end

-- Localization table with enUS fallback (same pattern as Ironman)
local L = {}
ns.L = L
ns.enUS = {}
local locale = GetLocale() or "enUS"

-- To test a specific locale, hard-code it here and uncomment the line.
--locale = "deDE"

setmetatable(L, {
    __index = function(t, k)
        local lt = ns[locale]
        if lt and lt[k] then
            rawset(t, k, lt[k]); return lt[k]
        elseif ns.enUS[k] then
            -- print("Fallback to enUS for key:", k)
            rawset(t, k, ns.enUS[k]); return ns.enUS[k]
        else
            -- print("Missing translation for key:", k)
            rawset(t, k, k); return k
        end
    end
})

-- English (enUS)
ns["enUS"] = {
    all_equipped_ok = "All equipped items are OK",
    allow_help = "Allow an item you specify",
    auction_disallowed = "You cannot use the auction house",
    bad_item_link_s = function(s) return "Unable to parse item link: " .. s end,
    bank_disallowed = "You cannot use the bank",
    bank_help = function(level) return "Allow or disallow using the bank (decide before level " .. level .. ")" end,
    bank_off = "Using the bank is now forbidden",
    bank_on = "Using the bank is now allowed",
    cannot_cast_s = function(name) return "You cannot cast " .. name end,
    cannot_equip_s = function(link) return "You cannot use " .. link end,
    disallow_help = "Disallow an item you specify",
    hearth_disallowed = "You cannot hearth - please destroy your hearthstone",
    hearth_help = function(level) return "Allow or disallow using a hearthstone (decide before level " .. level .. ")" end,
    hearth_off = "Hearthing is now forbidden",
    hearth_on = "Hearthing is now allowed",
    id_name_link = "id/name/link",
    init_base = "No dying, no trading, no mail, no auction house, no quest rewards, no buying from vendors (with a few exceptions)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "hearthing OK" or "no hearthing") .. ", " .. (bankOK and "banking OK" or "no banking") end,
    init_tip = function(cmd) return "Initialized: type " .. cmd .. " for more info" end,
    item_not_found_s = function(s) return "Item not found: " .. s end,
    level_too_high = "Your level is too high to change that",
    mail_activated = "You can now use mail for one minute",
    mail_already_activated = "Mail is already activated for one minute",
    mail_deactivated = "One minute has elapsed: mail is now deactivated",
    mail_disallowed = "You cannot use mail",
    mail_help = "Allow using mail for one minute (for quests only)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") now allowed" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") now disallowed" end,
    prefix = "SCAVENGER: ", -- One space at the end
    trade_activated = "You can now trade for one minute",
    trade_already_activated = "Trading is already activated for one minute",
    trade_deactivated = "One minute has elapsed: trading is now deactivated",
    trade_disallowed = "You cannot trade",
    trade_help = "Allow trading for one minute (for emergencies only)",
    unequip_n_quest_items = function(n) return "Unequip " .. n .. " quest items" end,
    unequip_quest_item_s = function(link) return "Unequip quest item " .. link end,

}

-- German (deDE)
ns["deDE"] = {
    all_equipped_ok = "Alle angelegten Gegenstände sind erlaubt",
    allow_help = "Erlaube einen von dir angegebenen Gegenstand",
    auction_disallowed = "Du kannst das Auktionshaus nicht benutzen",
    bad_item_link_s = function(s) return "Gegenstandslink konnte nicht verarbeitet werden: " .. s end,
    bank_disallowed = "Du kannst die Bank nicht benutzen",
    bank_help = function(level) return "Benutzung der Bank erlauben oder verbieten (entscheide dich vor Stufe " .. level .. ")" end,
    bank_off = "Die Benutzung der Bank ist jetzt verboten",
    bank_on = "Die Benutzung der Bank ist jetzt erlaubt",
    cannot_cast_s = function(name) return "Du kannst " .. name .. " nicht wirken" end,
    cannot_equip_s = function(link) return "Du kannst " .. link .. " nicht benutzen" end,
    disallow_help = "Verbiete einen von dir angegebenen Gegenstand",
    hearth_disallowed = "Du kannst keinen Ruhestein benutzen – bitte zerstöre deinen Ruhestein",
    hearth_help = function(level) return "Benutzung eines Ruhesteins erlauben oder verbieten (entscheide dich vor Stufe " .. level .. ")" end,
    hearth_off = "Ruhesteinbenutzung ist jetzt verboten",
    hearth_on = "Ruhesteinbenutzung ist jetzt erlaubt",
    id_name_link = "id/Name/Link",
    init_base = "Kein Sterben, kein Handeln, keine Post, kein Auktionshaus, keine Questbelohnungen, kein Kaufen bei Händlern (mit wenigen Ausnahmen)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "Ruhestein erlaubt" or "kein Ruhestein") .. ", " .. (bankOK and "Bank erlaubt" or "keine Bank") end,
    init_tip = function(cmd) return "Initialisiert: Tippe " .. cmd .. " für mehr Infos" end,
    item_not_found_s = function(s) return "Gegenstand nicht gefunden: " .. s end,
    level_too_high = "Deine Stufe ist zu hoch, um das zu ändern",
    mail_activated = "Du kannst jetzt eine Minute lang die Post benutzen",
    mail_already_activated = "Post ist bereits für eine Minute aktiviert",
    mail_deactivated = "Eine Minute ist vorbei: Post ist jetzt deaktiviert",
    mail_disallowed = "Du kannst die Post nicht benutzen",
    mail_help = "Post für eine Minute erlauben (nur für Quests)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") jetzt erlaubt" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") jetzt verboten" end,
    prefix = "SCAVENGER: ",
    trade_activated = "Du kannst jetzt eine Minute lang handeln",
    trade_already_activated = "Handeln ist bereits für eine Minute aktiviert",
    trade_deactivated = "Eine Minute ist vorbei: Handeln ist jetzt deaktiviert",
    trade_disallowed = "Du kannst nicht handeln",
    trade_help = "Handeln für eine Minute erlauben (nur für Notfälle)",
    unequip_n_quest_items = function(n) return "Lege " .. n .. " Questgegenstände ab" end,
    unequip_quest_item_s = function(link) return "Lege Questgegenstand " .. link .. " ab" end,
}

-- Spanish (esES)
ns["esES"] = {
    all_equipped_ok = "Todos los objetos equipados están permitidos",
    allow_help = "Permitir un objeto que especifiques",
    auction_disallowed = "No puedes usar la casa de subastas",
    bad_item_link_s = function(s) return "No se pudo analizar el enlace de objeto: " .. s end,
    bank_disallowed = "No puedes usar el banco",
    bank_help = function(level) return "Permitir o prohibir el uso del banco (decidir antes del nivel " .. level .. ")" end,
    bank_off = "El uso del banco ahora está prohibido",
    bank_on = "El uso del banco ahora está permitido",
    cannot_cast_s = function(name) return "No puedes lanzar " .. name end,
    cannot_equip_s = function(link) return "No puedes usar " .. link end,
    disallow_help = "Prohibir un objeto que especifiques",
    hearth_disallowed = "No puedes usar la piedra de hogar – por favor destruye tu piedra de hogar",
    hearth_help = function(level) return "Permitir o prohibir el uso de la piedra de hogar (decidir antes del nivel " .. level .. ")" end,
    hearth_off = "El uso de la piedra de hogar ahora está prohibido",
    hearth_on = "El uso de la piedra de hogar ahora está permitido",
    id_name_link = "id/nombre/enlace",
    init_base = "No morir, no comerciar, sin correo, sin casa de subastas, sin recompensas de misiones, no comprar en vendedores (con algunas excepciones)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "piedra de hogar permitida" or "sin piedra de hogar") .. ", " .. (bankOK and "banco permitido" or "sin banco") end,
    init_tip = function(cmd) return "Inicializado: escribe " .. cmd .. " para más información" end,
    item_not_found_s = function(s) return "Objeto no encontrado: " .. s end,
    level_too_high = "Tu nivel es demasiado alto para cambiar eso",
    mail_activated = "Ahora puedes usar el correo durante un minuto",
    mail_already_activated = "El correo ya está activado durante un minuto",
    mail_deactivated = "Un minuto ha pasado: el correo ahora está desactivado",
    mail_disallowed = "No puedes usar el correo",
    mail_help = "Permitir usar el correo durante un minuto (solo para misiones)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") ahora permitido" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") ahora prohibido" end,
    prefix = "SCAVENGER: ",
    trade_activated = "Ahora puedes comerciar durante un minuto",
    trade_already_activated = "El comercio ya está activado durante un minuto",
    trade_deactivated = "Un minuto ha pasado: el comercio ahora está desactivado",
    trade_disallowed = "No puedes comerciar",
    trade_help = "Permitir comerciar durante un minuto (solo en emergencias)",
    unequip_n_quest_items = function(n) return "Quítate " .. n .. " objetos de misión" end,
    unequip_quest_item_s = function(link) return "Quítate el objeto de misión " .. link end,
}

-- French (frFR)
ns["frFR"] = {
    all_equipped_ok = "Tous les objets équipés sont autorisés",
    allow_help = "Autoriser un objet que vous spécifiez",
    auction_disallowed = "Vous ne pouvez pas utiliser l'hôtel des ventes",
    bad_item_link_s = function(s) return "Impossible d’analyser le lien d’objet : " .. s end,
    bank_disallowed = "Vous ne pouvez pas utiliser la banque",
    bank_help = function(level) return "Autoriser ou interdire l’utilisation de la banque (décider avant le niveau " .. level .. ")" end,
    bank_off = "L’utilisation de la banque est maintenant interdite",
    bank_on = "L’utilisation de la banque est maintenant autorisée",
    cannot_cast_s = function(name) return "Vous ne pouvez pas lancer " .. name end,
    cannot_equip_s = function(link) return "Vous ne pouvez pas utiliser " .. link end,
    disallow_help = "Interdire un objet que vous spécifiez",
    hearth_disallowed = "Vous ne pouvez pas utiliser votre pierre de foyer – veuillez détruire votre pierre de foyer",
    hearth_help = function(level) return "Autoriser ou interdire l’utilisation de la pierre de foyer (décider avant le niveau " .. level .. ")" end,
    hearth_off = "L’utilisation de la pierre de foyer est maintenant interdite",
    hearth_on = "L’utilisation de la pierre de foyer est maintenant autorisée",
    id_name_link = "id/nom/lien",
    init_base = "Pas de mort, pas d’échanges, pas de courrier, pas d’hôtel des ventes, pas de récompenses de quêtes, pas d’achats chez les marchands (sauf quelques exceptions)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "pierre de foyer autorisée" or "pas de pierre de foyer") .. ", " .. (bankOK and "banque autorisée" or "pas de banque") end,
    init_tip = function(cmd) return "Initialisé : tapez " .. cmd .. " pour plus d’informations" end,
    item_not_found_s = function(s) return "Objet introuvable : " .. s end,
    level_too_high = "Votre niveau est trop élevé pour changer cela",
    mail_activated = "Vous pouvez maintenant utiliser le courrier pendant une minute",
    mail_already_activated = "Le courrier est déjà activé pour une minute",
    mail_deactivated = "Une minute s’est écoulée : le courrier est maintenant désactivé",
    mail_disallowed = "Vous ne pouvez pas utiliser le courrier",
    mail_help = "Autoriser l’utilisation du courrier pendant une minute (uniquement pour les quêtes)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") maintenant autorisé" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") maintenant interdit" end,
    prefix = "SCAVENGER : ",
    trade_activated = "Vous pouvez maintenant échanger pendant une minute",
    trade_already_activated = "L’échange est déjà activé pour une minute",
    trade_deactivated = "Une minute s’est écoulée : l’échange est maintenant désactivé",
    trade_disallowed = "Vous ne pouvez pas échanger",
    trade_help = "Autoriser les échanges pendant une minute (uniquement en cas d’urgence)",
    unequip_n_quest_items = function(n) return "Retirez " .. n .. " objets de quête" end,
    unequip_quest_item_s = function(link) return "Retirez l’objet de quête " .. link end,
}

-- Italian (itIT)
ns["itIT"] = {
    all_equipped_ok = "Tutti gli oggetti equipaggiati sono consentiti",
    allow_help = "Permetti un oggetto specificato",
    auction_disallowed = "Non puoi usare la casa d'aste",
    bad_item_link_s = function(s) return "Impossibile analizzare il collegamento all’oggetto: " .. s end,
    bank_disallowed = "Non puoi usare la banca",
    bank_help = function(level) return "Permetti o proibisci l'uso della banca (decidi prima del livello " .. level .. ")" end,
    bank_off = "L'uso della banca è ora proibito",
    bank_on = "L'uso della banca è ora consentito",
    cannot_cast_s = function(name) return "Non puoi lanciare " .. name end,
    cannot_equip_s = function(link) return "Non puoi usare " .. link end,
    disallow_help = "Proibisci un oggetto specificato",
    hearth_disallowed = "Non puoi usare la pietra del ritorno – per favore distruggila",
    hearth_help = function(level) return "Permetti o proibisci l'uso della pietra del ritorno (decidi prima del livello " .. level .. ")" end,
    hearth_off = "La pietra del ritorno è ora proibita",
    hearth_on = "La pietra del ritorno è ora consentita",
    id_name_link = "id/nome/link",
    init_base = "Niente morti, niente scambi, niente posta, niente casa d’aste, niente ricompense delle missioni, niente acquisti dai mercanti (con poche eccezioni)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "pietra del ritorno consentita" or "nessuna pietra del ritorno") .. ", " .. (bankOK and "banca consentita" or "nessuna banca") end,
    init_tip = function(cmd) return "Inizializzato: digita " .. cmd .. " per maggiori informazioni" end,
    item_not_found_s = function(s) return "Oggetto non trovato: " .. s end,
    level_too_high = "Il tuo livello è troppo alto per modificare questo",
    mail_activated = "Ora puoi usare la posta per un minuto",
    mail_already_activated = "La posta è già attivata per un minuto",
    mail_deactivated = "Un minuto è passato: la posta è ora disattivata",
    mail_disallowed = "Non puoi usare la posta",
    mail_help = "Permetti di usare la posta per un minuto (solo per missioni)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") ora consentito" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") ora proibito" end,
    prefix = "SCAVENGER: ",
    trade_activated = "Ora puoi commerciare per un minuto",
    trade_already_activated = "Il commercio è già attivato per un minuto",
    trade_deactivated = "Un minuto è passato: il commercio è ora disattivato",
    trade_disallowed = "Non puoi commerciare",
    trade_help = "Permetti di commerciare per un minuto (solo in caso di emergenza)",
    unequip_n_quest_items = function(n) return "Rimuovi " .. n .. " oggetti di missione" end,
    unequip_quest_item_s = function(link) return "Rimuovi l'oggetto di missione " .. link end,
}

-- Russian (ruRU)
ns["ruRU"] = {
    all_equipped_ok = "Все надетые предметы допустимы",
    allow_help = "Разрешить указанный предмет",
    auction_disallowed = "Вы не можете пользоваться аукционом",
    bad_item_link_s = function(s) return "Не удалось разобрать ссылку на предмет: " .. s end,
    bank_disallowed = "Вы не можете пользоваться банком",
    bank_help = function(level) return "Разрешить или запретить использование банка (решить до уровня " .. level .. ")" end,
    bank_off = "Использование банка теперь запрещено",
    bank_on = "Использование банка теперь разрешено",
    cannot_cast_s = function(name) return "Вы не можете применить " .. name end,
    cannot_equip_s = function(link) return "Вы не можете использовать " .. link end,
    disallow_help = "Запретить указанный предмет",
    hearth_disallowed = "Вы не можете использовать камень возвращения – пожалуйста уничтожьте его",
    hearth_help = function(level) return "Разрешить или запретить использование камня возвращения (решить до уровня " .. level .. ")" end,
    hearth_off = "Использование камня возвращения теперь запрещено",
    hearth_on = "Использование камня возвращения теперь разрешено",
    id_name_link = "id/имя/ссылка",
    init_base = "Без смертей, без торговли, без почты, без аукциона, без наград за задания, без покупок у торговцев (с некоторыми исключениями)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "камень возвращения разрешен" or "без камня возвращения") .. ", " .. (bankOK and "банк разрешен" or "без банка") end,
    init_tip = function(cmd) return "Инициализировано: введите " .. cmd .. " для дополнительной информации" end,
    item_not_found_s = function(s) return "Предмет не найден: " .. s end,
    level_too_high = "Ваш уровень слишком высок, чтобы это изменить",
    mail_activated = "Теперь вы можете использовать почту в течение одной минуты",
    mail_already_activated = "Почта уже активирована на одну минуту",
    mail_deactivated = "Прошла одна минута: почта теперь деактивирована",
    mail_disallowed = "Вы не можете пользоваться почтой",
    mail_help = "Разрешить использование почты на одну минуту (только для заданий)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") теперь разрешен" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") теперь запрещен" end,
    prefix = "SCAVENGER: ",
    trade_activated = "Теперь вы можете торговать в течение одной минуты",
    trade_already_activated = "Торговля уже активирована на одну минуту",
    trade_deactivated = "Прошла одна минута: торговля теперь деактивирована",
    trade_disallowed = "Вы не можете торговать",
    trade_help = "Разрешить торговлю на одну минуту (только для экстренных случаев)",
    unequip_n_quest_items = function(n) return "Снимите " .. n .. " предметов задания" end,
    unequip_quest_item_s = function(link) return "Снимите предмет задания " .. link end,
}

-- Traditional Chinese (zhTW)
ns["zhTW"] = {
    all_equipped_ok = "所有已裝備的物品都可以使用",
    allow_help = "允許指定的物品",
    auction_disallowed = "你不能使用拍賣場",
    bad_item_link_s = function(s) return "無法解析物品連結: " .. s end,
    bank_disallowed = "你不能使用銀行",
    bank_help = function(level) return "允許或禁止使用銀行（必須在等級 " .. level .. " 前決定）" end,
    bank_off = "現在禁止使用銀行",
    bank_on = "現在允許使用銀行",
    cannot_cast_s = function(name) return "你不能施放 " .. name end,
    cannot_equip_s = function(link) return "你不能使用 " .. link end,
    disallow_help = "禁止指定的物品",
    hearth_disallowed = "你不能使用爐石 – 請銷毀你的爐石",
    hearth_help = function(level) return "允許或禁止使用爐石（必須在等級 " .. level .. " 前決定）" end,
    hearth_off = "現在禁止使用爐石",
    hearth_on = "現在允許使用爐石",
    id_name_link = "id/名稱/連結",
    init_base = "禁止死亡，禁止交易，禁止郵件，禁止拍賣場，禁止任務獎勵，禁止向商人購買（少數例外）",
    init_desc = function(hearthOK, bankOK) return L.init_base .. "，" .. (hearthOK and "爐石允許" or "禁止爐石") .. "，" .. (bankOK and "銀行允許" or "禁止銀行") end,
    init_tip = function(cmd) return "已初始化：輸入 " .. cmd .. " 以取得更多資訊" end,
    item_not_found_s = function(s) return "找不到物品: " .. s end,
    level_too_high = "你的等級太高，無法更改此項",
    mail_activated = "你現在可以使用郵件一分鐘",
    mail_already_activated = "郵件已啟用一分鐘",
    mail_deactivated = "一分鐘已過：郵件現在停用",
    mail_disallowed = "你不能使用郵件",
    mail_help = "允許使用郵件一分鐘（僅限任務）",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") 現在允許" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") 現在禁止" end,
    prefix = "SCAVENGER: ",
    trade_activated = "你現在可以交易一分鐘",
    trade_already_activated = "交易已啟用一分鐘",
    trade_deactivated = "一分鐘已過：交易現在停用",
    trade_disallowed = "你不能交易",
    trade_help = "允許交易一分鐘（僅限緊急情況）",
    unequip_n_quest_items = function(n) return "卸下 " .. n .. " 個任務物品" end,
    unequip_quest_item_s = function(link) return "卸下任務物品 " .. link end,
}

-- Korean (koKR)
ns["koKR"] = {
    all_equipped_ok = "착용한 모든 아이템은 허용됩니다",
    allow_help = "지정한 아이템을 허용합니다",
    auction_disallowed = "경매장을 사용할 수 없습니다",
    bad_item_link_s = function(s) return "아이템 링크를 해석할 수 없습니다: " .. s end,
    bank_disallowed = "은행을 사용할 수 없습니다",
    bank_help = function(level) return "은행 사용을 허용하거나 금지합니다 (레벨 " .. level .. " 이전에 결정)" end,
    bank_off = "은행 사용이 이제 금지되었습니다",
    bank_on = "은행 사용이 이제 허용되었습니다",
    cannot_cast_s = function(name) return name .. "을(를) 시전할 수 없습니다" end,
    cannot_equip_s = function(link) return link .. " 을(를) 사용할 수 없습니다" end,
    disallow_help = "지정한 아이템을 금지합니다",
    hearth_disallowed = "귀환석을 사용할 수 없습니다 – 귀환석을 파기하세요",
    hearth_help = function(level) return "귀환석 사용을 허용하거나 금지합니다 (레벨 " .. level .. " 이전에 결정)" end,
    hearth_off = "귀환석 사용이 이제 금지되었습니다",
    hearth_on = "귀환석 사용이 이제 허용되었습니다",
    id_name_link = "id/이름/링크",
    init_base = "죽음 금지, 거래 금지, 우편 금지, 경매장 금지, 퀘스트 보상 금지, 상인에게서 구매 금지 (일부 예외 있음)",
    init_desc = function(hearthOK, bankOK) return L.init_base .. ", " .. (hearthOK and "귀환석 허용" or "귀환석 금지") .. ", " .. (bankOK and "은행 허용" or "은행 금지") end,
    init_tip = function(cmd) return "초기화됨: " .. cmd .. " 입력 시 더 많은 정보 제공" end,
    item_not_found_s = function(s) return "아이템을 찾을 수 없습니다: " .. s end,
    level_too_high = "해당 변경을 하기에는 레벨이 너무 높습니다",
    mail_activated = "이제 1분 동안 우편을 사용할 수 있습니다",
    mail_already_activated = "우편이 이미 1분간 활성화되어 있습니다",
    mail_deactivated = "1분이 지났습니다: 우편이 이제 비활성화되었습니다",
    mail_disallowed = "우편을 사용할 수 없습니다",
    mail_help = "우편을 1분 동안 허용합니다 (퀘스트 전용)",
    now_allowed_s_i = function(link, id) return link .. " (" .. id .. ") 이제 허용됨" end,
    now_disallowed_s_i = function(link, id) return link .. " (" .. id .. ") 이제 금지됨" end,
    prefix = "SCAVENGER: ",
    trade_activated = "이제 1분 동안 거래할 수 있습니다",
    trade_already_activated = "거래가 이미 1분간 활성화되어 있습니다",
    trade_deactivated = "1분이 지났습니다: 거래가 이제 비활성화되었습니다",
    trade_disallowed = "거래할 수 없습니다",
    trade_help = "1분 동안 거래 허용 (비상시에만)",
    unequip_n_quest_items = function(n) return n .. "개의 퀘스트 아이템을 해제하세요" end,
    unequip_quest_item_s = function(link) return "퀘스트 아이템 " .. link .. " 을(를) 해제하세요" end,
}
